### ISSUE TITLE
Ability to better specify what the previous commit is

### ISSUE THREAD

**Issue by rwilcox** [Crimix/ChangedProjectsTaskPlugin#1]
Hey this is awesome! Thank you so much for the project AND the very clear "add these 10 lines to your Gradle script to try this out", because I _did_ want to quickly test it out and not play fight the Gradle to do it.

I have one kind of small issue: the previous commit stuff is kind of awkward for my use case.

What I want to do is run this in CI jobs testing branches. I want to know what changes have been made since that branch diverged from the main branch. Thus CI can focus on those modules only, and Do Things(TM).

In [ChangedFilesProvider](https://github.com/Crimix/ChangedProjectsTaskPlugin/blob/e32899948b26daf9530b015af37dfecb2cc3ed45/src/main/java/io/github/crimix/changedprojectstask/providers/ChangedFilesProvider.java#L52) you get the user's specified previous commit, then always add "~" to it.

This does show what changed in only the current commit, but I want to see what's happened in the entire branch.

To do this by hand in git diff I could do `git diff main HEAD --name-only` (which works!) OR get fancy and use the [dotted range notations from git-ref](https://git-scm.com/docs/git-rev-parse#_dotted_range_notations) - also where I got docs about `~`.

**But**:

  1. ChangedProjectsTaskPlugin `initCommitIds` forces a ~ when I give it a previous commit, getting the previous commit to that. If I specify `main` then I get a diff INCLUDING the last commit on main AND my branch. 

  2. or if I did want to do dotted ranges, [`initFilteredChanges`](https://github.com/Crimix/ChangedProjectsTaskPlugin/blob/e32899948b26daf9530b015af37dfecb2cc3ed45/src/main/java/io/github/crimix/changedprojectstask/providers/ChangedFilesProvider.java#L76) prevents me (it is "%s %s")

Would you be willing to either add such a use case, or accept a PR that provides it, if I did it?

**Comment by Crimix** [comment]
Thanks for the feedback.
Glad you liked the "how to test it part"

Would a switch to decide how the previous and current behavior work be fine.

Like a `-PcommitCompareMode=("branch"|"commit"|"branchTwoDotted")` with "commit" being the default.

This way I would not add the ~ to the previous, but leave it be and either add the dots or not.

**Comment by rwilcox** [comment]
> Would a switch to decide how the previous and current behavior work be fine.

Yes, that would be excellent! We squash merge so running this on `main` the way it works now is awesome... except it's not _quite_ there for pull request workflows use case.

**Comment by Crimix** [comment]
Alright, I will probably start working on it this weekend

**Comment by Crimix** [comment]
I have published version 1.2 with the changes we discussed, please check the read me for more information 😄

**Comment by rwilcox** [comment]
OK this looks awesome! I can't wait to try to hook this up on Monday!!!!!!!

**Comment by rwilcox** [comment]
This is awesome, thank you very much!!!!!
