### ISSUE TITLE
Allow taskToRun to be passed as a command line argument via -PchangedProjectsTask.taskToRun

### ISSUE THREAD

**Issue by mklueh** [Crimix/ChangedProjectsTaskPlugin#5]
I thought I'd open a new issue for this one :)

It would be handy if you could just pass the task you want to run as an command-line argument. That way you can run multiple tasks with this plugin via CI.

```
    private String getPathToTask(Project project) {
        String taskToRun = Extensions
                .getTaskToRunParameter(project)
                .orElse(extension.getTaskToRun().getOrNull());

        if (project.isRootProject()) {
            return String.format(":%s", taskToRun);
        } else {
            return String.format("%s:%s", project.getPath(), taskToRun);
        }
    }
```

```
    public static Optional<String> getTaskToRunParameter(Project project) {
        return Optional.of(project)
                .map(Project::getRootProject)
                .map(p -> p.findProperty(TASK_TO_RUN))
                .map(String.class::cast);
    }
```

Not tested yet and not sure if this works.

**Comment by Crimix** [comment]
I will look into it and see if it makes sense at some point

**Comment by mklueh** [comment]
@Crimix Let me give you an example I have in mind: My intention was to trigger the axion plugin with it https://axion-release-plugin.readthedocs.io/ besides the build command

axion is a plugin that automatically applies semantic versioning and is able to raise versions when modules have changed.

The problem with axion is, it won't detect changes of submodules and it does also not allow - when sumodules have changed to version the applications

If commands via arguments would be possible with your plugin, it could be used to explicitly generate versions for all directly changed applications and for applications where submodules have changed :)


so I would instead of this command (which generates all versions of all changed modules

```
      - name: generate versions of changed applications
        run: |
          gradle --continue release \
              -Prelease.customUsername=${{ github.actor }} \
              -Prelease.customPassword=${{ github.token }}
```

use it this way


```
      - name: generate versions changed applications and those where submodules have changed
        run: |
            gradle --continue runTaskForChangedProjects -PchangedProjectsTask.run -PchangedProjectsTask.taskToRun=release \
              -Prelease.customUsername=${{ github.actor }} \
              -Prelease.customPassword=${{ github.token }}
```

And of course, as a separate Github Actions step the build command

```
      - name: build and release changed applications and those where submodules have changed
        run: |
            gradle --continue runTaskForChangedProjects -PchangedProjectsTask.run -PchangedProjectsTask.taskToRun=build \
                      -Dquarkus.container-image.build=true 
                      -Dquarkus.container-image.push=true 
                      -Dquarkus.jib.base-registry-password=${{ secrets.GITHUB_TOKEN }} 
                      -Dquarkus.jib.base-registry-username=${{ github.repository_owner }}
```

**Comment by Crimix** [comment]
That makes sense, I will try to implement it
